#!/usr/bin/env bash
# =============================================================================
# bootstrap.sh — Dotfiles installer for macOS
# Run on a fresh Mac: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/YOU/dotfiles/main/bootstrap.sh)"
# =============================================================================

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${BLUE}▶ $*${RESET}"; }
success() { echo -e "${GREEN}✓ $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠ $*${RESET}"; }
error()   { echo -e "${RED}✗ $*${RESET}"; exit 1; }
header()  { echo -e "\n${BOLD}${BLUE}━━━ $* ━━━${RESET}\n"; }

DOTFILES_DIR="$HOME/.dotfiles"
GITHUB_USER="${GITHUB_USER:-sjlouji}"   # override: GITHUB_USER=joan ./bootstrap.sh

# ── 1. Detect Machine ─────────────────────────────────────────────────────────
header "Detecting machine"

ARCH=$(uname -m)
OS_VERSION=$(sw_vers -productVersion)
HOSTNAME=$(hostname -s)
CURRENT_USER=$(whoami)

if [[ "$ARCH" == "arm64" ]]; then
  BREW_PREFIX="/opt/homebrew"
  CHIP="Apple Silicon"
else
  BREW_PREFIX="/usr/local"
  CHIP="Intel"
fi

info "Host:    $HOSTNAME"
info "User:    $CURRENT_USER"
info "macOS:   $OS_VERSION"
info "Chip:    $CHIP ($ARCH)"
info "Brew:    $BREW_PREFIX"

# ── 2. Machine Role ───────────────────────────────────────────────────────────
header "Machine identity"

if [[ -f "$DOTFILES_DIR/.local/machine.sh" ]]; then
  warn "machine.sh already exists — skipping identity setup"
  source "$DOTFILES_DIR/.local/machine.sh"
else
  echo -e "${BOLD}Which machine is this?${RESET}"
  echo "  [1] personal"
  echo "  [2] work"
  echo "  [3] other"
  read -rp "→ " ROLE_CHOICE

  case "$ROLE_CHOICE" in
    1) MACHINE_ROLE="personal" ;;
    2) MACHINE_ROLE="work" ;;
    3)
      read -rp "  Name this machine role: " MACHINE_ROLE
      ;;
    *) MACHINE_ROLE="personal" ;;
  esac

  if [[ "$MACHINE_ROLE" == "work" ]]; then
    read -rp "  Work git email: " GIT_EMAIL
    read -rp "  Work git name:  " GIT_NAME
  else
    read -rp "  Personal git email: " GIT_EMAIL
    read -rp "  Personal git name:  " GIT_NAME
  fi

  success "Role: $MACHINE_ROLE"
fi

# ── 3. Xcode CLI Tools ────────────────────────────────────────────────────────
header "Xcode CLI tools"

if ! xcode-select -p &>/dev/null; then
  info "Installing Xcode CLI tools..."
  xcode-select --install
  # Wait for install to complete
  until xcode-select -p &>/dev/null; do sleep 5; done
  success "Xcode CLI tools installed"
else
  success "Xcode CLI tools already present"
fi

# ── 4. Homebrew ───────────────────────────────────────────────────────────────
header "Homebrew"

if ! command -v brew &>/dev/null; then
  info "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$("$BREW_PREFIX/bin/brew" shellenv)"
  success "Homebrew installed"
else
  eval "$("$BREW_PREFIX/bin/brew" shellenv)"
  success "Homebrew already present"
fi

# ── 5. Clone Dotfiles ─────────────────────────────────────────────────────────
header "Dotfiles repo"

if [[ ! -d "$DOTFILES_DIR" ]]; then
  # Install gh cli first so we can auth
  brew install gh git 2>/dev/null || true

  info "Authenticating with GitHub..."
  gh auth login

  info "Cloning dotfiles..."
  gh repo clone "$GITHUB_USER/dotfiles" "$DOTFILES_DIR"
  success "Dotfiles cloned to $DOTFILES_DIR"
else
  info "Dotfiles already cloned — pulling latest..."
  git -C "$DOTFILES_DIR" pull --rebase --autostash
  success "Dotfiles up to date"
fi

# ── 6. Write machine.sh ───────────────────────────────────────────────────────
header "Writing machine identity"

mkdir -p "$DOTFILES_DIR/.local"

if [[ ! -f "$DOTFILES_DIR/.local/machine.sh" ]]; then
  cat > "$DOTFILES_DIR/.local/machine.sh" <<EOF
# Auto-generated by bootstrap.sh on $(date)
# DO NOT commit this file — it is gitignored
export MACHINE_ROLE="${MACHINE_ROLE}"
export MACHINE_NAME="${HOSTNAME}"
export MACHINE_USER="${CURRENT_USER}"
export MACHINE_ARCH="${ARCH}"
export BREW_PREFIX="${BREW_PREFIX}"
export GIT_EMAIL="${GIT_EMAIL:-}"
export GIT_NAME="${GIT_NAME:-}"
export DOTFILES_DIR="${DOTFILES_DIR}"
EOF
  success "machine.sh written"
fi

# ── 7. Homebrew Bundle ────────────────────────────────────────────────────────
header "Installing packages (Brewfile)"

brew bundle --file="$DOTFILES_DIR/Brewfile" || warn "Some Brewfile items failed — check output above"

# Machine-local extras
if [[ -f "$DOTFILES_DIR/.local/Brewfile.local" ]]; then
  info "Installing machine-local brews..."
  brew bundle --file="$DOTFILES_DIR/.local/Brewfile.local"
fi

success "Homebrew bundle complete"

# ── 8. Oh My Zsh ─────────────────────────────────────────────────────────────
header "Oh My Zsh"

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  info "Installing Oh My Zsh..."
  RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  success "Oh My Zsh installed"
else
  success "Oh My Zsh already present"
fi

# Install plugins
ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"

if [[ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
fi

if [[ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
fi

if [[ ! -d "$ZSH_CUSTOM/plugins/you-should-use" ]]; then
  git clone https://github.com/MichaelAquilina/zsh-you-should-use "$ZSH_CUSTOM/plugins/you-should-use"
fi

success "Zsh plugins installed"

# ── 9. Symlinks ───────────────────────────────────────────────────────────────
header "Creating symlinks"

bash "$DOTFILES_DIR/scripts/symlink.sh"

# ── 10. Set Default Shell ─────────────────────────────────────────────────────
header "Default shell"

ZSH_PATH="$BREW_PREFIX/bin/zsh"
if [[ "$SHELL" != "$ZSH_PATH" ]]; then
  if ! grep -qF "$ZSH_PATH" /etc/shells; then
    echo "$ZSH_PATH" | sudo tee -a /etc/shells
  fi
  chsh -s "$ZSH_PATH"
  success "Default shell set to $ZSH_PATH"
else
  success "Already using $ZSH_PATH"
fi

# ── 11. VS Code Extensions ────────────────────────────────────────────────────
header "VS Code extensions"

if command -v code &>/dev/null; then
  while IFS= read -r ext; do
    [[ -z "$ext" || "$ext" == \#* ]] && continue
    code --install-extension "$ext" --force 2>/dev/null || warn "Failed: $ext"
  done < "$DOTFILES_DIR/vscode/extensions.txt"
  success "VS Code extensions installed"
else
  warn "VS Code 'code' CLI not found — skipping extensions (install VS Code first)"
fi

# ── 12. macOS Defaults ────────────────────────────────────────────────────────
header "Applying macOS defaults"

bash "$DOTFILES_DIR/macos/defaults.sh"
success "macOS defaults applied"

# ── 13. SSH Key ───────────────────────────────────────────────────────────────
header "SSH key"

if [[ ! -f "$HOME/.ssh/id_ed25519" ]]; then
  bash "$DOTFILES_DIR/scripts/ssh-keygen.sh"
else
  success "SSH key already exists at ~/.ssh/id_ed25519"
fi

# ── 14. Register Auto-Sync LaunchAgent ───────────────────────────────────────
header "Dotfiles auto-sync"

PLIST_SRC="$DOTFILES_DIR/macos/com.dotfiles.sync.plist"
PLIST_DEST="$HOME/Library/LaunchAgents/com.dotfiles.sync.plist"

if [[ -f "$PLIST_SRC" ]]; then
  cp "$PLIST_SRC" "$PLIST_DEST"
  launchctl load "$PLIST_DEST" 2>/dev/null || true
  success "Auto-sync LaunchAgent registered"
fi

# ── 15. Install git hooks ─────────────────────────────────────────────────────
header "Git hooks"

GIT_HOOKS_DIR="$DOTFILES_DIR/.git/hooks"
cp "$DOTFILES_DIR/sync/hooks/post-merge"  "$GIT_HOOKS_DIR/post-merge"
cp "$DOTFILES_DIR/sync/hooks/pre-push"    "$GIT_HOOKS_DIR/pre-push"
chmod +x "$GIT_HOOKS_DIR/post-merge" "$GIT_HOOKS_DIR/pre-push"
success "Git hooks installed"

# ── Done ──────────────────────────────────────────────────────────────────────
header "Bootstrap complete"

echo -e "${GREEN}${BOLD}"
echo "  ✓ Machine identity: $MACHINE_ROLE ($HOSTNAME)"
echo "  ✓ Homebrew + packages installed"
echo "  ✓ Oh My Zsh + plugins"
echo "  ✓ All symlinks created"
echo "  ✓ VS Code extensions"
echo "  ✓ macOS defaults applied"
echo "  ✓ Auto-sync registered"
echo ""
echo "  Next steps:"
echo "  1. Add your SSH key to GitHub → run: cat ~/.ssh/id_ed25519.pub"
echo "  2. Restart your terminal"
echo "  3. Run 'dsync status' to verify sync is working"
echo -e "${RESET}"
