#!/usr/bin/env bash
# =============================================================================
# scripts/setup/git.sh — Git identity setup for all GitHub accounts
#
# Standalone usage:  bash ~/.dotfiles/scripts/setup/git.sh
# Via bootstrap:     bootstrap.sh git
#
# Writes per-account .gitconfig-<username> files and regenerates
# .gitconfig-accounts with the correct [includeIf] routing rules.
# =============================================================================

set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
source "$DOTFILES_DIR/scripts/setup/lib.sh"

header "Git identity"

detect_machine
ensure_accounts

mkdir -p "$DOTFILES_DIR/.local"

# Write per-account identity files (skip if already exist)
for i in "${!GH_USERNAMES[@]}"; do
  GH_USER="${GH_USERNAMES[$i]}"
  GH_NAME="${GH_NAMES[$i]}"
  GH_EMAIL="${GH_EMAILS[$i]}"
  GH_FOLDER="${GH_FOLDERS[$i]}"
  GITCFG="$DOTFILES_DIR/.local/.gitconfig-${GH_USER}"

  if [[ ! -f "$GITCFG" ]]; then
    cat > "$GITCFG" <<EOF
[user]
  name  = ${GH_NAME}
  email = ${GH_EMAIL}
EOF
    success "Git identity: @${GH_USER} → ~/${GH_FOLDER}/"
  else
    warn ".gitconfig-${GH_USER} already exists — skipping (delete to regenerate)"
  fi
done

# Always regenerate .gitconfig-accounts to reflect the current account list
ACCOUNTS_CFG="$DOTFILES_DIR/.local/.gitconfig-accounts"
{
  echo "# Auto-generated by setup/git.sh on $(date)"
  echo "# GitHub account identity routing — loaded via .gitconfig.local"
  echo "# Edit account folders here or re-run: bootstrap.sh git"
  echo ""
  for i in "${!GH_USERNAMES[@]}"; do
    GH_USER="${GH_USERNAMES[$i]}"
    GH_FOLDER="${GH_FOLDERS[$i]}"
    echo "# @${GH_USER} → ~/${GH_FOLDER}/"
    echo "[includeIf \"gitdir:~/${GH_FOLDER}/\"]"
    echo "  path = ~/.dotfiles/.local/.gitconfig-${GH_USER}"
    echo ""
  done
} > "$ACCOUNTS_CFG"
success ".gitconfig-accounts written (${#GH_USERNAMES[@]} account(s))"

# Write .gitconfig.local if it doesn't already exist
if [[ ! -f "$DOTFILES_DIR/.local/.gitconfig.local" ]]; then
  cat > "$DOTFILES_DIR/.local/.gitconfig.local" <<EOF
# Machine-local git config for ${HOSTNAME}
# Generated by bootstrap.sh — safe to edit manually

[include]
  path = ~/.dotfiles/.local/.gitconfig-accounts
EOF
  success ".gitconfig.local written"
fi

echo ""
success "Git identity setup complete"
echo ""
echo "  Run 'git whoami' in any repo to confirm which identity is active."
for i in "${!GH_USERNAMES[@]}"; do
  echo "    ~/${GH_FOLDERS[$i]}/  →  ${GH_NAMES[$i]} <${GH_EMAILS[$i]}>"
done
