#!/usr/bin/env bash
# =============================================================================
# scripts/setup/ssh.sh — SSH key setup for all GitHub accounts
#
# Standalone usage:  bash ~/.dotfiles/scripts/setup/ssh.sh
# Via bootstrap:     bootstrap.sh ssh
#
# For each GitHub account stored in machine.sh (or collected interactively):
#   - Generates an ed25519 key: ~/.ssh/id_ed25519_<username>
#   - Asks whether to regenerate if a key already exists
#   - Stores the passphrase in Apple Keychain (no prompts after first unlock)
#   - Writes a Host alias to .local/ssh_accounts.conf
#   - Offers to auto-add the public key to GitHub via gh CLI
# =============================================================================

set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
source "$DOTFILES_DIR/scripts/setup/lib.sh"

header "SSH keys"

detect_machine
ensure_accounts

mkdir -p "$HOME/.ssh/control"
chmod 700 "$HOME/.ssh"

SERIAL=$(system_profiler SPHardwareDataType 2>/dev/null | awk '/Serial Number/{print $NF}')
SSH_KEY_ID="${HOSTNAME}-${SERIAL}"

SSH_ACCOUNTS_CONF="$DOTFILES_DIR/.local/ssh_accounts.conf"
mkdir -p "$DOTFILES_DIR/.local"

# Always rebuild the conf file from scratch so it stays in sync with accounts
{
  echo "# Auto-generated by setup/ssh.sh on $(date)"
  echo "# GitHub SSH host aliases — one per account"
  echo "# Usage: git clone git@github-<username>:org/repo.git"
  echo ""
} > "$SSH_ACCOUNTS_CONF"

for i in "${!GH_USERNAMES[@]}"; do
  GH_USER="${GH_USERNAMES[$i]}"
  GH_EMAIL="${GH_EMAILS[$i]}"
  KEY_PATH="$HOME/.ssh/id_ed25519_${GH_USER}"

  echo ""
  info "SSH key for @${GH_USER}"

  GENERATE_KEY=true

  if [[ -f "$KEY_PATH" ]]; then
    warn "Key already exists: ~/.ssh/id_ed25519_${GH_USER}"
    read -rp "  Generate a new key for @${GH_USER}? [y/N]: " REGEN
    if [[ "$REGEN" =~ ^[Yy]$ ]]; then
      rm -f "$KEY_PATH" "${KEY_PATH}.pub"
      info "Existing key removed"
    else
      GENERATE_KEY=false
    fi
  fi

  if [[ "$GENERATE_KEY" == true ]]; then
    echo ""
    echo "  Generating ed25519 key for @${GH_USER}..."
    echo "  Enter a passphrase when prompted — it will be saved to Apple Keychain."
    echo "  Leave blank only if you intentionally want no passphrase."
    echo ""
    ssh-keygen -t ed25519 -C "${GH_EMAIL} (${SSH_KEY_ID})" -f "$KEY_PATH"
    success "Key generated: ~/.ssh/id_ed25519_${GH_USER}"
  fi

  # Store passphrase in Apple Keychain — no more prompts after this
  echo ""
  info "Loading key into Apple Keychain..."
  if ssh-add --apple-use-keychain "$KEY_PATH" 2>/dev/null; then
    success "Passphrase stored in Apple Keychain"
  else
    ssh-add "$KEY_PATH" 2>/dev/null \
      || warn "Could not load key — run manually: ssh-add --apple-use-keychain ~/.ssh/id_ed25519_${GH_USER}"
  fi

  # Write host alias block into ssh_accounts.conf
  cat >> "$SSH_ACCOUNTS_CONF" <<EOF
# @${GH_USER}
Host github-${GH_USER}
  HostName      github.com
  User          git
  IdentityFile  ~/.ssh/id_ed25519_${GH_USER}

EOF

  success "SSH alias: github-${GH_USER} → @${GH_USER}"

  # Display public key
  echo ""
  echo -e "  ${BOLD}Public key for @${GH_USER}:${RESET}"
  echo "  ──────────────────────────────────────────────────────────"
  cat "${KEY_PATH}.pub"
  echo "  ──────────────────────────────────────────────────────────"
  echo ""

  # Offer to auto-add to GitHub
  if command -v gh &>/dev/null; then
    read -rp "  Auto-add to GitHub (@${GH_USER}) via gh CLI? [y/N]: " AUTOADD
    if [[ "$AUTOADD" =~ ^[Yy]$ ]]; then
      # Ensure we're authenticated as the correct GitHub account.
      # Each account needs its own session; `gh auth switch` handles already-logged-in users.
      CURRENT_GH_USER=$(gh api user --jq .login 2>/dev/null || echo "")
      if [[ "$CURRENT_GH_USER" != "$GH_USER" ]]; then
        if ! gh auth switch --user "$GH_USER" 2>/dev/null; then
          info "Authenticating @${GH_USER} via browser (one-time per account)..."
          gh auth login --hostname github.com --git-protocol https --web --scopes admin:public_key
        fi
      fi

      if gh ssh-key add "${KEY_PATH}.pub" --title "${SSH_KEY_ID} ($(date +%Y-%m-%d))"; then
        success "SSH key added to GitHub @${GH_USER}"
      else
        warn "Upload failed — run manually:"
        echo "  gh auth refresh -h github.com -s admin:public_key"
        echo "  gh ssh-key add ${KEY_PATH}.pub --title \"${SSH_KEY_ID}\""
        echo "  Or add at: https://github.com/settings/ssh/new"
      fi
    else
      echo "  → Add manually: https://github.com/settings/ssh/new"
    fi
  else
    echo "  → Add manually: https://github.com/settings/ssh/new"
  fi
done

echo ""
success "SSH setup complete"
echo ""
echo "  Clone repos using:"
for i in "${!GH_USERNAMES[@]}"; do
  echo "    git clone git@github-${GH_USERNAMES[$i]}:${GH_USERNAMES[$i]}/repo.git"
done
